title: "Programacion Web"
remote_theme: just-the-docs/just-the-docs
# theme: "just-the-docs"
search_enabled: false
logo: "/assets/images/logo.png"
heading_anchors: true
color_scheme: cird

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Importante
    color: blue
  concept:
    title: Concepo clave
    color: green
  note:
    title: Nota
    color: purple